name = "database-test"
compatibility_date = "2025-10-07"
main = "src/index.js"

[[d1_databases]]
binding = "DB"
database_name = "todo_db"
database_id = "37f238ca-5608-4fd8-a5d6-fc89593e9dcc"

[site]
bucket = "./public"
